version: '3.7'

services: 
  postgres: 
    image: posgres:alpine
    restart: always
    env_file:
      - .env
    ports: 
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
volumes: 
  postgresql-volume:
    external: true

